# Site settings
title: CoderDojo Passau
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Die CoderDojo Gemeinschaft organisiert Programmierclubs für Kinder und Jugendliche zwischen 7 und 17 Jahren. Diese Seite ist für die CoderDojos Passau.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://gofraser.github.io/coderdojo-passau/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude: ["bin", "bower_components", "jekyll", "node_modules", "obj", "styles/sass/*.*", "typings", "coderdojo-passau.*", "*.json", "app.*", "Gulpfile.js"]
